// Life narrative — v1.4. A short, plain-language summary of the user's current
// state across the four domains, generated by Gemini via the `ai-generate`
// Supabase Edge Function (the on-device path is unavailable on the S24 — see
// the AI-1 registry blocker). The key lives server-side; this just sends a
// prompt built from already-derived Life-score signals.
//
// Privacy: the prompt carries only aggregate 0–100 sub-scores and the
// already-on-screen pattern headlines — no transaction descriptions, amounts,
// account numbers, names, or other raw PII.
//
// Always degrades gracefully: any failure (AI not configured, offline, rate
// limit, blocked) returns null and the card simply doesn't render.

import { supabase } from './supabase';
import { type LifeProfile, type DomainKey } from './lifeProfile';

export interface NarrativeInput {
  /** Composite life score, 0–100. */
  lifeScore: number;
  /** Domain sub-scores, each 0–100. */
  workouts: number;
  study: number;
  habits: number;
  budget: number;
  /** v1.5 — Work domain sub-score, 0–100. Optional for back-compat. */
  work?: number;
  /** v1.5 — active Life Profile. When present, the prompt covers only the
   *  profile's enabled domains (so Professional talks about Work not Studies,
   *  Custom covers whatever's enabled). Absent → legacy 4-domain prompt. */
  profile?: LifeProfile;
  /** Headlines of the cross-domain patterns already surfaced on the Life tab. */
  insightHeadlines: string[];
}

function buildPrompt(input: NarrativeInput): string {
  const band = (n: number) =>
    n >= 75 ? 'strong' : n >= 50 ? 'steady' : n >= 25 ? 'slipping' : 'low';
  const patterns = input.insightHeadlines.length
    ? input.insightHeadlines.map((h) => `- ${h}`).join('\n')
    : '- (no notable cross-domain patterns this week)';

  // Build the domain lines from the active profile when present; otherwise
  // fall back to the legacy fixed four (Fitness/Studies/Habits/Budget).
  const LINES: Record<DomainKey, string> = {
    finance: `- Budget: ${band(input.budget)}`,
    fitness: `- Fitness: ${band(input.workouts)}`,
    studies: `- Studies: ${band(input.study)}`,
    work: `- Work: ${band(input.work ?? 0)}`,
    habits: `- Habits: ${band(input.habits)}`,
  };
  const order: DomainKey[] = ['finance', 'fitness', 'studies', 'work', 'habits'];
  const domainLines = input.profile
    ? order.filter((k) => input.profile!.domains[k] > 0).map((k) => LINES[k])
    : [LINES.fitness, LINES.studies, LINES.habits, LINES.finance];

  return `You are a personal life-dashboard assistant. Write 2–3 short sentences summarising this person's current week across life domains. Be specific, plain-language, and honest without being harsh or preachy. Do NOT mention numbers, scores, or percentages — translate them into concrete, human observations. Don't give a numbered list; write flowing prose. Don't invent facts beyond the data.

Domain standing this week (qualitative band in brackets):
${domainLines.join('\n')}

Patterns already detected:
${patterns}

Write the summary now:`;
}

/**
 * Generate the Life narrative via the server-side Gemini proxy. Returns the
 * trimmed text, or null on any failure (so the caller hides the card).
 */
export async function generateLifeNarrative(input: NarrativeInput): Promise<string | null> {
  try {
    const { data, error } = await supabase.functions.invoke<{ text?: string; error?: string }>(
      'ai-generate',
      { body: { prompt: buildPrompt(input), maxTokens: 200, temperature: 0.6 } },
    );
    if (error) return null;
    const text = data?.text?.trim();
    return text && text.length > 0 ? text : null;
  } catch {
    return null;
  }
}
