import Dexie, { Table } from 'dexie';
import { Transaction, BudgetCategory, PortfolioHolding, PortfolioLot, ApiCacheEntry, PortfolioSnapshot, ManualAsset, WatchlistItem, SavingsGoal, StockSale, PortfolioCashEntry } from '../types/finance';
import { Course, Grade, GradeImport, StudySession } from '../types/studies';
import { WorkoutSession, WorkoutSet, BodyMetric } from '../types/fitness';
import { Task } from '../types/tasks';
import { Goal } from '../types/goals';
import { Habit, HabitCompletion } from '../types/habits';
import { WorkQualityLog } from '../types/work';
import { generateId } from '../utils/uuid';

// v1.2 — Insights rating-history row. One per recompute per ticker. Used to
// detect tier changes between consecutive recomputes (gating the push
// notification) and to power any future "rating drift" chart.
export interface RatingHistoryEntry {
  /** Composite key: `${ticker}:${computedAt}` — keeps the table chronological
   *  and prevents accidental dupes when two recomputes land in the same ms. */
  id: string;
  ticker: string;
  /** ISO timestamp. */
  computedAt: string;
  score: number;
  tier: string;
  /** JSON-serialized breakdown for the rating-over-time chart in a future
   *  release. We don't query into this column; storing as a string keeps
   *  Dexie's index footprint tiny. */
  breakdownJson: string;
}

// v1.2 follow-up — BUG-9. Latest composite Insights score per (ticker, kind).
// Distinct from `ratingHistory` above — that's a chronological log used for
// tier-change detection / notification cooldown. THIS table holds exactly
// one row per (ticker, kind), upserted on every successful recompute, so the
// in-memory ratings/fundamentals maps in `useInsightsStore` can re-hydrate
// on cold start BEFORE the sweep-tier guards run. Without this hydration,
// the daily/weekly sweep guards short-circuit (still within window), the
// maps stay empty, and the UI shows blank pills until the user manually
// hits Refresh — which was the BUG-9 symptom.
export interface InsightScoreRow {
  /** Synthesised `${kind}:${ticker}` so put() upserts cleanly. */
  id: string;
  ticker: string;
  kind: 'technical' | 'fundamental';
  score: number;
  tier: string;
  partial: boolean;
  /** JSON-serialised CompositeBreakdown | FundamentalBreakdown — we don't
   *  query into it, just rehydrate the full rating shape. */
  breakdownJson: string;
  computedAt: string;
}

// v1.4 — cached Life narrative. Single-row table (id always = 1). The
// narrative is generated by the `ai-generate` Edge Function (cloud Gemini)
// and cached locally so the Life tab shows it instantly on revisit without a
// network round-trip; regenerated when the life score drifts ≥5 points.
export interface LifeNarrativeRow {
  id: number;          // always 1
  text: string;
  generatedAt: string; // ISO
  lifeScore: number;   // composite at generation time, for drift detection
}

export interface SyncQueueItem {
  id: string;
  entityType:
    | 'transaction'
    | 'budget_category'
    | 'portfolio_holding'
    | 'course'
    | 'grade'
    | 'grade_import'
    | 'workout_session'
    | 'workout_set'
    | 'task'
    | 'study_session'
    | 'portfolio_lot'
    | 'manual_asset'
    | 'watchlist_item'
    | 'goal'
    | 'habit'
    | 'habit_completion'
    | 'stock_sale'
    | 'portfolio_cash_entry'
    | 'work_quality_log';
  entityId: string;
  operation: 'insert' | 'update' | 'delete';
  payload: string;
  createdAt: string;
  syncedAt?: string;
  lastError?: string;
}

class NexusDB extends Dexie {
  transactions!: Table<Transaction, string>;
  budgetCategories!: Table<BudgetCategory, string>;
  portfolioHoldings!: Table<PortfolioHolding, string>;
  apiCache!: Table<ApiCacheEntry, string>;

  gradeImports!: Table<GradeImport, string>;
  courses!: Table<Course, string>;
  // v7 — per-assessment grade rows. StudyDesk grades each carry their own
  // weight + date; storing them separately lets a subject have many grades
  // and lets us compute accurate GPAs (weighted across grades, then weighted
  // across subjects by credits).
  grades!: Table<Grade, string>;

  workoutSessions!: Table<WorkoutSession, string>;
  workoutSets!: Table<WorkoutSet, string>;

  tasks!: Table<Task, string>;

  // v2-B
  studySessions!: Table<StudySession, string>;
  // v1.4 — the `readings` table was dropped in Dexie v17 (Reading Log
  // feature retired). No `readings` Table accessor remains.

  // v2-C — local-only series of total portfolio value sampled once per day
  // on refresh. Keyed by YYYY-MM-DD so a same-day refresh upserts cleanly.
  portfolioSnapshots!: Table<PortfolioSnapshot, string>;

  // v2-D — purchase lots. Each row is one buy event for one holding.
  portfolioLots!: Table<PortfolioLot, string>;

  // v3 — net worth + watchlist
  manualAssets!: Table<ManualAsset, string>;
  watchlistItems!: Table<WatchlistItem, string>;

  // v3-Phase5 — goals (cross-module targets derived from existing data)
  goals!: Table<Goal, string>;

  // v8 — Insights rating history (v1.2). One row per recompute per ticker
  // that produced a usable result. Used for tier-change detection (compare
  // latest vs previous tier per ticker) + the future "rating over time"
  // chart. Local-only, no cloud sync.
  ratingHistory!: Table<RatingHistoryEntry, string>;

  // v9 — Savings Goals (v1.2). Named goals with a target amount that the
  // user allocates toward from their cash+savings ManualAssets. Local-only
  // for v1.2 (sync queue entry shape doesn't include 'savings_goal' yet —
  // future v1.3 work).
  savingsGoals!: Table<SavingsGoal, string>;

  // v11 — Habit Tracker (v1.2). Habits live in Supabase + Dexie with full
  // realtime sync (entity types 'habit' + 'habit_completion'). Completions
  // are one-per-habit-per-date (UNIQUE constraint at the DB), keyed locally
  // by their UUID id with a (habitId, date) compound index for the
  // by-date toggle/lookup.
  habits!: Table<Habit, string>;
  habitCompletions!: Table<HabitCompletion, string>;

  // v13 — BUG-9 Insights persistence. One row per (ticker, kind), upserted
  // on every successful Insights recompute. Hydrated on cold start before
  // the sweep-tier guards run, so the UI shows scores immediately even when
  // the daily/weekly recompute window hasn't elapsed.
  insightsScores!: Table<InsightScoreRow, string>;

  // v14 — LimeLog body metrics, READ-ONLY in NCC (v1.3). One row per
  // (user, date) pulled from the LimeLog-owned `body_metrics` Supabase table.
  // NCC displays the weight trend + measurements on the Fitness screen; it
  // never writes here (no syncQueue entityType). Realtime already wired the
  // body_metrics subscription in v1.2.1 (AUDIT-FSG-5); this table is where
  // that pull lands (the AUDIT-FSG-5b residual — pullAll had nowhere to put
  // body metrics until this table existed).
  bodyMetrics!: Table<BodyMetric, string>;
  workQualityLogs!: Table<WorkQualityLog, string>;

  // v15 — BUG-23 Stock Sales Tracking (v1.3.1). One row per realized sale.
  // FIFO cost basis computed at sale time; realized P&L is Σ realizedGainLoss.
  stockSales!: Table<StockSale, string>;

  // v16 — Portfolio cash ledger (v1.3.2). Append-only signed cash movements
  // (buy/sell/deposit/withdrawal). Balance = Σ(amount→base). See
  // PortfolioCashEntry in types/finance.ts.
  portfolioCashEntries!: Table<PortfolioCashEntry, string>;

  // v18 — Life narrative cache (v1.4). Single-row, local-only.
  lifeNarrative!: Table<LifeNarrativeRow, number>;

  syncQueue!: Table<SyncQueueItem, string>;

  constructor() {
    super('nexus_dashboard');
    this.version(1).stores({
      transactions: 'id, date, type, syncStatus',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      syncQueue: 'id, entityType, syncedAt',
    });
    // v2 — Dexie migrates additively; existing tables are untouched and the
    // two new tables come up empty for current users. The pull-from-cloud
    // path populates them on next sync.
    this.version(2).stores({
      transactions: 'id, date, type, syncStatus',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      studySessions: 'id, startedAt, subjectId, syncStatus',
      readings: 'id, status, subjectId, updatedAt',
      syncQueue: 'id, entityType, syncedAt',
    });
    // v3 — additive: adds portfolioSnapshots (local-only). Existing tables
    // are untouched, the new table comes up empty for current users.
    this.version(3).stores({
      transactions: 'id, date, type, syncStatus',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      studySessions: 'id, startedAt, subjectId, syncStatus',
      readings: 'id, status, subjectId, updatedAt',
      portfolioSnapshots: 'date',
      syncQueue: 'id, entityType, syncedAt',
    });
    // v4 — adds portfolioLots (purchase lots). Existing single-avg-cost
    // holdings continue to work; on first load we synthesize a lot for any
    // holding that has avgCostNative + quantity set, so P/L keeps rendering.
    this.version(4).stores({
      transactions: 'id, date, type, syncStatus',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      studySessions: 'id, startedAt, subjectId, syncStatus',
      readings: 'id, status, subjectId, updatedAt',
      portfolioSnapshots: 'date',
      portfolioLots: 'id, holdingId, purchaseDate, syncStatus',
      syncQueue: 'id, entityType, syncedAt',
    });
    // v5 — adds manualAssets + watchlistItems. Existing tables untouched.
    this.version(5).stores({
      transactions: 'id, date, type, syncStatus',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      studySessions: 'id, startedAt, subjectId, syncStatus',
      readings: 'id, status, subjectId, updatedAt',
      portfolioSnapshots: 'date',
      portfolioLots: 'id, holdingId, purchaseDate, syncStatus',
      manualAssets: 'id, assetType, syncStatus',
      watchlistItems: 'id, ticker, assetType, syncStatus',
      syncQueue: 'id, entityType, syncedAt',
    });
    // v6 — adds goals. Cross-module targets, derived from existing data.
    this.version(6).stores({
      transactions: 'id, date, type, syncStatus',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      studySessions: 'id, startedAt, subjectId, syncStatus',
      readings: 'id, status, subjectId, updatedAt',
      portfolioSnapshots: 'date',
      portfolioLots: 'id, holdingId, purchaseDate, syncStatus',
      manualAssets: 'id, assetType, syncStatus',
      watchlistItems: 'id, ticker, assetType, syncStatus',
      goals: 'id, goalType, completed, targetDate, syncStatus',
      syncQueue: 'id, entityType, syncedAt',
    });
    // v7 — adds `grades` table so a subject can carry multiple grades, each
    // with its own weight + date. Faithfully mirrors StudyDesk's grades table.
    //
    // Upgrade hook migrates existing single-grade Courses by synthesizing one
    // Grade row per Course (using the course's stored `grade` and a default
    // weight of 1) and copies legacy `weight` → `credits` on the Course so
    // the new field name has a value going forward.
    this.version(7).stores({
      transactions: 'id, date, type, syncStatus',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      studySessions: 'id, startedAt, subjectId, syncStatus',
      readings: 'id, status, subjectId, updatedAt',
      portfolioSnapshots: 'date',
      portfolioLots: 'id, holdingId, purchaseDate, syncStatus',
      manualAssets: 'id, assetType, syncStatus',
      watchlistItems: 'id, ticker, assetType, syncStatus',
      goals: 'id, goalType, completed, targetDate, syncStatus',
      grades: 'id, subjectId, date, syncStatus',
      syncQueue: 'id, entityType, syncedAt',
    }).upgrade(async (tx) => {
      const coursesTable = tx.table('courses');
      const gradesTable = tx.table('grades');
      const existing = await coursesTable.toArray();
      const now = new Date().toISOString();
      const synthesized: Grade[] = [];
      for (const c of existing) {
        // Synthesize a Grade row from the legacy course.grade field, if set.
        const legacyGrade = (c as { grade?: unknown }).grade;
        if (typeof legacyGrade === 'number' && !isNaN(legacyGrade)) {
          synthesized.push({
            id: `legacy-${c.id}`,
            subjectId: c.id,
            grade: legacyGrade,
            weight: 1,
            date:
              typeof c.createdAt === 'string'
                ? c.createdAt.slice(0, 10)
                : undefined,
            syncStatus: 'synced',
            createdAt: c.createdAt ?? now,
            updatedAt: c.createdAt ?? now,
          });
        }
        // Copy legacy `weight` → `credits` if `credits` not already set.
        const legacyWeight = (c as { weight?: unknown }).weight;
        const hasCredits =
          (c as { credits?: unknown }).credits != null &&
          typeof (c as { credits?: unknown }).credits === 'number';
        if (!hasCredits && typeof legacyWeight === 'number') {
          (c as { credits?: number }).credits = legacyWeight;
          await coursesTable.put(c);
        } else if (!hasCredits) {
          (c as { credits?: number }).credits = 1;
          await coursesTable.put(c);
        }
      }
      if (synthesized.length) await gradesTable.bulkAdd(synthesized);
    });
    // v9 — adds `savingsGoals` for v1.2 Savings Goals. Additive (no upgrade
    // hook); existing tables untouched. Versions must be declared in
    // ascending order, so this lives AFTER the v8 block below.
    //
    // (Declared first in source because the constructor reads top-down; the
    // ACTUAL declaration happens after v8 with `.stores({...})` — see below.)

    // v8 — adds `ratingHistory` for v1.2 Insights tier-change detection.
    // Additive (no upgrade hook needed); existing tables untouched. Comes
    // AFTER v7 because Dexie requires version declarations in ascending order.
    this.version(8).stores({
      transactions: 'id, date, type, syncStatus',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      studySessions: 'id, startedAt, subjectId, syncStatus',
      readings: 'id, status, subjectId, updatedAt',
      portfolioSnapshots: 'date',
      portfolioLots: 'id, holdingId, purchaseDate, syncStatus',
      manualAssets: 'id, assetType, syncStatus',
      watchlistItems: 'id, ticker, assetType, syncStatus',
      goals: 'id, goalType, completed, targetDate, syncStatus',
      grades: 'id, subjectId, date, syncStatus',
      // [ticker+computedAt] compound index lets us efficiently fetch the
      // most-recent entry per ticker without scanning the whole table.
      ratingHistory: 'id, ticker, computedAt, [ticker+computedAt]',
      syncQueue: 'id, entityType, syncedAt',
    });
    // v9 — adds `savingsGoals` for v1.2. Additive — no upgrade hook needed.
    this.version(9).stores({
      transactions: 'id, date, type, syncStatus',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      studySessions: 'id, startedAt, subjectId, syncStatus',
      readings: 'id, status, subjectId, updatedAt',
      portfolioSnapshots: 'date',
      portfolioLots: 'id, holdingId, purchaseDate, syncStatus',
      manualAssets: 'id, assetType, syncStatus',
      watchlistItems: 'id, ticker, assetType, syncStatus',
      goals: 'id, goalType, completed, targetDate, syncStatus',
      grades: 'id, subjectId, date, syncStatus',
      ratingHistory: 'id, ticker, computedAt, [ticker+computedAt]',
      // Indexes: id (PK), completedAt (sort/filter), createdAt (audit trail).
      // No need to index targetAmount/allocatedAmount — full table scan over
      // a typical handful of goals is essentially free.
      savingsGoals: 'id, completedAt, createdAt, syncStatus',
      syncQueue: 'id, entityType, syncedAt',
    });

    // v10 — v1.2.2 Library refactor (Lent → Borrowed-from-library). Same
    // schema (no field is indexed among the changed ones), but the shelf
    // literal flipped from 'lent' → 'borrowed' and the metadata fields
    // renamed (lentTo → borrowedFrom, lentAt → borrowedAt). The upgrade
    // hook rewrites existing readings rows so the UI doesn't have to
    // handle both shapes. expectedReturnAt is unchanged (same name + same
    // semantic — a due date).
    this.version(10).stores({
      transactions: 'id, date, type, syncStatus',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      studySessions: 'id, startedAt, subjectId, syncStatus',
      readings: 'id, status, subjectId, updatedAt',
      portfolioSnapshots: 'date',
      portfolioLots: 'id, holdingId, purchaseDate, syncStatus',
      manualAssets: 'id, assetType, syncStatus',
      watchlistItems: 'id, ticker, assetType, syncStatus',
      goals: 'id, goalType, completed, targetDate, syncStatus',
      grades: 'id, subjectId, date, syncStatus',
      ratingHistory: 'id, ticker, computedAt, [ticker+computedAt]',
      savingsGoals: 'id, completedAt, createdAt, syncStatus',
      syncQueue: 'id, entityType, syncedAt',
    }).upgrade(async (tx) => {
      // Map old → new on every existing readings row. `toCollection().modify`
      // is the canonical Dexie pattern for in-place row rewrites. Touch only
      // the fields that actually need changing — others stay untouched so
      // the user's notes/ratings/progress remain intact.
      await tx.table('readings').toCollection().modify((r) => {
        if (r.shelf === 'lent') r.shelf = 'borrowed';
        if (r.lentTo !== undefined) {
          r.borrowedFrom = r.lentTo;
          delete r.lentTo;
        }
        if (r.lentAt !== undefined) {
          r.borrowedAt = r.lentAt;
          delete r.lentAt;
        }
      });
    });

    // v11 — Habit Tracker (v1.2). Two additive tables. The (habitId+date)
    // compound index serves the toggle-for-day lookup; the standalone date
    // index covers cross-domain weekly aggregation (Cross-Domain Insights).
    this.version(11).stores({
      transactions: 'id, date, type, syncStatus',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      studySessions: 'id, startedAt, subjectId, syncStatus',
      readings: 'id, status, subjectId, updatedAt',
      portfolioSnapshots: 'date',
      portfolioLots: 'id, holdingId, purchaseDate, syncStatus',
      manualAssets: 'id, assetType, syncStatus',
      watchlistItems: 'id, ticker, assetType, syncStatus',
      goals: 'id, goalType, completed, targetDate, syncStatus',
      grades: 'id, subjectId, date, syncStatus',
      ratingHistory: 'id, ticker, computedAt, [ticker+computedAt]',
      savingsGoals: 'id, completedAt, createdAt, syncStatus',
      habits: 'id, archivedAt, syncStatus, createdAt',
      habitCompletions: 'id, habitId, date, syncStatus, [habitId+date]',
      syncQueue: 'id, entityType, syncedAt',
    });

    // ─── v12 — CTO Account-based finance refactor ─────────────────────────
    //
    // Two-pronged upgrade. Schema-wise it adds an `accountId` index on
    // transactions (the AccountDetail screen needs to query "all
    // transactions hitting account X" cheaply) and an `archivedAt` index
    // on manualAssets (Net Worth filters archived rows out of its primary
    // list). Everything else is data-only.
    //
    // Upgrade hook does the heavy lifting:
    //   1. Back-fill manualAssets rows with `accountType` (mapped from
    //      legacy `assetType` via legacyAssetTypeToAccountType) and
    //      `startingBalance` (copied from `value`). The legacy `assetType` +
    //      `value` fields stay on the row — see the type comment in
    //      `types/finance.ts` for the dual-field rationale.
    //   2. Back-fill transactions rows with `accountId` via a best-guess
    //      heuristic:
    //        a. If the transaction's category carries `linkedManualAssetId`
    //           (from my BUG-6 patch), use it.
    //        b. Else first cash-type account by createdAt.
    //        c. Else first checking-type account by createdAt.
    //        d. Else first account by createdAt.
    //        e. Else undefined (very fresh install with no accounts yet —
    //           the user reconciles via AddTransaction's account picker on
    //           the next edit).
    //   3. Leave the BudgetCategory rows alone — `linkedManualAssetId`
    //      semantics shift (auto-debit → pre-select-on-add) but the on-disk
    //      shape is identical.
    this.version(12).stores({
      // Transactions gain an `accountId` index for the AccountDetail screen.
      transactions: 'id, date, type, syncStatus, accountId',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      studySessions: 'id, startedAt, subjectId, syncStatus',
      readings: 'id, status, subjectId, updatedAt',
      portfolioSnapshots: 'date',
      portfolioLots: 'id, holdingId, purchaseDate, syncStatus',
      // ManualAssets table keeps its old name (data migration is enough; a
      // hard rename would force every consumer to update at the same
      // moment, which we want to avoid). archivedAt index added for the
      // soft-archive flow.
      manualAssets: 'id, assetType, syncStatus, archivedAt',
      watchlistItems: 'id, ticker, assetType, syncStatus',
      goals: 'id, goalType, completed, targetDate, syncStatus',
      grades: 'id, subjectId, date, syncStatus',
      ratingHistory: 'id, ticker, computedAt, [ticker+computedAt]',
      savingsGoals: 'id, completedAt, createdAt, syncStatus',
      habits: 'id, archivedAt, syncStatus, createdAt',
      habitCompletions: 'id, habitId, date, syncStatus, [habitId+date]',
      syncQueue: 'id, entityType, syncedAt',
    }).upgrade(async (tx) => {
      const { legacyAssetTypeToAccountType } = await import('../types/finance');
      const accountsTable = tx.table('manualAssets');
      const categoriesTable = tx.table('budgetCategories');
      const transactionsTable = tx.table('transactions');

      // Step 1 — back-fill the new field names on every existing
      // manualAssets row. Both old and new fields end up populated; new
      // code reads `accountType` / `startingBalance`, legacy code keeps
      // reading `assetType` / `value` until the cleanup sweep.
      await accountsTable.toCollection().modify((row) => {
        if (row.accountType == null) {
          row.accountType = legacyAssetTypeToAccountType(row.assetType);
        }
        if (row.startingBalance == null) {
          row.startingBalance = typeof row.value === 'number' ? row.value : 0;
        }
      });

      // Step 2 — best-guess back-fill for `accountId` on every existing
      // transaction. Fetch categories + accounts once; iterate transactions.
      const categories = (await categoriesTable.toArray()) as Array<{
        id: string;
        linkedManualAssetId?: string;
      }>;
      const accounts = (await accountsTable.toArray()) as Array<{
        id: string;
        accountType?: string;
        assetType?: string;
        createdAt: string;
      }>;
      accounts.sort((a, b) =>
        (a.createdAt ?? '').localeCompare(b.createdAt ?? ''),
      );
      const firstByType = (...types: string[]): string | undefined => {
        for (const t of types) {
          const hit = accounts.find(
            (a) => a.accountType === t || a.assetType === t,
          );
          if (hit) return hit.id;
        }
        return undefined;
      };
      const defaultAccountId =
        firstByType('cash') ??
        firstByType('checking') ??
        accounts[0]?.id;

      await transactionsTable.toCollection().modify((t) => {
        if (t.accountId) return; // already migrated
        const cat = t.categoryId
          ? categories.find((c) => c.id === t.categoryId)
          : null;
        // (a) Category's BUG-6 link gets first crack — it's the closest
        // thing to an existing "intended account" signal we have.
        if (cat?.linkedManualAssetId) {
          t.accountId = cat.linkedManualAssetId;
          return;
        }
        // (b-d) Fall through to the global default.
        if (defaultAccountId) {
          t.accountId = defaultAccountId;
        }
        // (e) No accounts at all → leave undefined; AddTransaction will
        // require an account on the next edit.
      });
    });

    // ─── v13 — BUG-9 Insights score persistence ──────────────────────────
    //
    // Additive — one new `insightsScores` table. No upgrade hook needed;
    // existing users come up with an empty table and the first successful
    // recompute pass populates it. Until that first pass lands, the UI
    // behaves exactly as it did pre-fix (blank pills until recompute).
    //
    // Why a separate table from `ratingHistory`:
    //   - `ratingHistory` is a chronological append-only log used by the
    //     tier-change notification path (cooldown + drift chart). It
    //     accumulates indefinitely (one row per recompute per ticker).
    //   - `insightsScores` is a flat snapshot — exactly one row per
    //     (ticker, kind). put() upserts in place; the table size scales
    //     with the universe, not with time.
    //
    // PK = `${kind}:${ticker}` so each kind has its own slot per ticker.
    // Indexes: ticker (per-ticker queries), kind (filter by tab), computedAt
    // (future "last computed N hours ago" header strip).
    this.version(13).stores({
      transactions: 'id, date, type, syncStatus, accountId',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      studySessions: 'id, startedAt, subjectId, syncStatus',
      readings: 'id, status, subjectId, updatedAt',
      portfolioSnapshots: 'date',
      portfolioLots: 'id, holdingId, purchaseDate, syncStatus',
      manualAssets: 'id, assetType, syncStatus, archivedAt',
      watchlistItems: 'id, ticker, assetType, syncStatus',
      goals: 'id, goalType, completed, targetDate, syncStatus',
      grades: 'id, subjectId, date, syncStatus',
      ratingHistory: 'id, ticker, computedAt, [ticker+computedAt]',
      savingsGoals: 'id, completedAt, createdAt, syncStatus',
      habits: 'id, archivedAt, syncStatus, createdAt',
      habitCompletions: 'id, habitId, date, syncStatus, [habitId+date]',
      insightsScores: 'id, ticker, kind, computedAt',
      syncQueue: 'id, entityType, syncedAt',
    });

    // ─── v14 — LimeLog body metrics (v1.3, read-only consumption) ─────────
    //
    // Additive — one new `bodyMetrics` table. No upgrade hook; existing users
    // come up empty and the body_metrics pull / realtime path populates it.
    // PK is the row's UUID (LimeLog-generated, stable across sync). `date`
    // index drives the chronological weight-trend query; `syncStatus` kept for
    // index-shape parity with the other synced tables (always 'synced' here).
    this.version(14).stores({
      transactions: 'id, date, type, syncStatus, accountId',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      studySessions: 'id, startedAt, subjectId, syncStatus',
      readings: 'id, status, subjectId, updatedAt',
      portfolioSnapshots: 'date',
      portfolioLots: 'id, holdingId, purchaseDate, syncStatus',
      manualAssets: 'id, assetType, syncStatus, archivedAt',
      watchlistItems: 'id, ticker, assetType, syncStatus',
      goals: 'id, goalType, completed, targetDate, syncStatus',
      grades: 'id, subjectId, date, syncStatus',
      ratingHistory: 'id, ticker, computedAt, [ticker+computedAt]',
      savingsGoals: 'id, completedAt, createdAt, syncStatus',
      habits: 'id, archivedAt, syncStatus, createdAt',
      habitCompletions: 'id, habitId, date, syncStatus, [habitId+date]',
      insightsScores: 'id, ticker, kind, computedAt',
      bodyMetrics: 'id, date, syncStatus',
      syncQueue: 'id, entityType, syncedAt',
    });

    // ─── v15 — BUG-23 Stock Sales Tracking (v1.3.1) ───────────────────────
    //
    // Adds the `stockSales` table (one row per realized sale) and a
    // non-indexed `soldShares` field on portfolioLots (FIFO consumption per
    // lot). soldShares isn't indexed, so the portfolioLots index string is
    // unchanged; the upgrade hook back-fills `soldShares = 0` on every
    // existing lot so `quantity - soldShares` is correct for legacy rows.
    this.version(15).stores({
      transactions: 'id, date, type, syncStatus, accountId',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      studySessions: 'id, startedAt, subjectId, syncStatus',
      readings: 'id, status, subjectId, updatedAt',
      portfolioSnapshots: 'date',
      portfolioLots: 'id, holdingId, purchaseDate, syncStatus',
      manualAssets: 'id, assetType, syncStatus, archivedAt',
      watchlistItems: 'id, ticker, assetType, syncStatus',
      goals: 'id, goalType, completed, targetDate, syncStatus',
      grades: 'id, subjectId, date, syncStatus',
      ratingHistory: 'id, ticker, computedAt, [ticker+computedAt]',
      savingsGoals: 'id, completedAt, createdAt, syncStatus',
      habits: 'id, archivedAt, syncStatus, createdAt',
      habitCompletions: 'id, habitId, date, syncStatus, [habitId+date]',
      insightsScores: 'id, ticker, kind, computedAt',
      bodyMetrics: 'id, date, syncStatus',
      stockSales: 'id, ticker, soldAt, syncStatus',
      syncQueue: 'id, entityType, syncedAt',
    }).upgrade(async (tx) => {
      // Back-fill soldShares = 0 on every existing lot (pre-sales-tracking
      // rows). New lots default via the store; this covers legacy data so
      // `quantity - (soldShares ?? 0)` is correct from first launch.
      await tx.table('portfolioLots').toCollection().modify((l) => {
        if (l.soldShares == null) l.soldShares = 0;
      });
    });

    // ─── v16 — Portfolio cash ledger (v1.3.2) ─────────────────────────────
    //
    // Additive — one new append-only `portfolioCashEntries` table. No upgrade
    // hook: existing users come up with an empty ledger (portfolio cash = 0),
    // which is exactly the start-at-zero / going-forward contract — pre-feature
    // holdings are treated as already funded; only new buys/sells/transfers
    // move cash from here on.
    this.version(16).stores({
      transactions: 'id, date, type, syncStatus, accountId',
      budgetCategories: 'id, name',
      portfolioHoldings: 'id, ticker, assetType',
      apiCache: 'cacheKey, expiresAt',
      gradeImports: 'id, importedAt',
      courses: 'id, importId, name',
      workoutSessions: 'id, date, sessionType, syncStatus',
      workoutSets: 'id, sessionId, exercise',
      tasks: 'id, dueDate, completed, priority, syncStatus',
      studySessions: 'id, startedAt, subjectId, syncStatus',
      readings: 'id, status, subjectId, updatedAt',
      portfolioSnapshots: 'date',
      portfolioLots: 'id, holdingId, purchaseDate, syncStatus',
      manualAssets: 'id, assetType, syncStatus, archivedAt',
      watchlistItems: 'id, ticker, assetType, syncStatus',
      goals: 'id, goalType, completed, targetDate, syncStatus',
      grades: 'id, subjectId, date, syncStatus',
      ratingHistory: 'id, ticker, computedAt, [ticker+computedAt]',
      savingsGoals: 'id, completedAt, createdAt, syncStatus',
      habits: 'id, archivedAt, syncStatus, createdAt',
      habitCompletions: 'id, habitId, date, syncStatus, [habitId+date]',
      insightsScores: 'id, ticker, kind, computedAt',
      bodyMetrics: 'id, date, syncStatus',
      stockSales: 'id, ticker, soldAt, syncStatus',
      portfolioCashEntries: 'id, type, createdAt, relatedId, syncStatus',
      syncQueue: 'id, entityType, syncedAt',
    });

    // ─── v17 — v1.4 Readings retirement ───────────────────────────────────
    //
    // The Reading Log / personal-library feature is retired. It had no entry
    // UI since BUG-16, and its return-to-library reminders fired broken
    // notifications. We drop the `readings` table outright (delta `null`),
    // and the upgrade hook also deletes any orphaned `reading_count` goals —
    // that GoalType was removed from the type system this version, so an
    // un-deleted row would render a missing label on the Goals screen. The
    // cloud delete is enqueued so the cleanup propagates to other devices and
    // a later pullAll doesn't resurrect the goal.
    this.version(17).stores({
      readings: null,
    }).upgrade(async (tx) => {
      const goalsTable = tx.table('goals');
      const queueTable = tx.table('syncQueue');
      const orphaned = await goalsTable
        .filter((g: { goalType?: string }) => g.goalType === 'reading_count')
        .toArray();
      const now = new Date().toISOString();
      for (const g of orphaned) {
        await goalsTable.delete(g.id);
        await queueTable.add({
          id: generateId(),
          entityType: 'goal',
          entityId: g.id,
          operation: 'delete',
          payload: JSON.stringify({ id: g.id }),
          createdAt: now,
        });
      }
    });

    // ─── v18 — Life narrative cache (v1.4) ────────────────────────────────
    //
    // Additive single-row table (id always = 1). No upgrade hook; comes up
    // empty and the first Life-tab visit populates it via the ai-generate
    // Edge Function. Local-only — never synced (it's derived, regenerable).
    this.version(18).stores({
      lifeNarrative: 'id',
    });

    // ─── v19 — Work domain (v1.5 Life Profile) ────────────────────────────
    //
    // Additive single table for the NCC-native Work domain: one daily
    // self-assessment per calendar day. `date` is indexed for fast weekly
    // lookups (the Work score reads the last 7 days). No upgrade hook — comes
    // up empty; cold-start hydrate + pullAll fill it from the cloud for
    // signed-in users on other devices.
    this.version(19).stores({
      workQualityLogs: 'id, date, syncStatus',
    });
  }
}

export const db = new NexusDB();

export async function clearAllLocalData(): Promise<void> {
  await db.transaction(
    'rw',
    [
      db.transactions,
      db.budgetCategories,
      db.portfolioHoldings,
      db.apiCache,
      db.gradeImports,
      db.courses,
      db.grades,
      db.workoutSessions,
      db.workoutSets,
      db.tasks,
      db.studySessions,
      db.portfolioSnapshots,
      db.portfolioLots,
      db.manualAssets,
      db.watchlistItems,
      db.goals,
      db.ratingHistory,
      db.savingsGoals,
      db.habits,
      db.habitCompletions,
      db.insightsScores,
      db.bodyMetrics,
      db.stockSales,
      db.portfolioCashEntries,
      db.lifeNarrative,
      db.workQualityLogs,
      db.syncQueue,
    ],
    async () => {
      await Promise.all([
        db.transactions.clear(),
        db.budgetCategories.clear(),
        db.portfolioHoldings.clear(),
        db.apiCache.clear(),
        db.gradeImports.c