import { SyncStatus } from './finance';

// Open-ended split label (push/pull/legs, upper/lower, full body, cardio,
// or anything custom the user enters).
export type WorkoutType = string;

export interface WorkoutSet {
  id: string;
  sessionId: string;
  exercise: string;
  weightKg?: number;
  reps?: number;
  rpe?: number;
  createdAt: string;
}

export interface WorkoutSession {
  id: string;
  sessionType: WorkoutType;
  date: string;
  sets: WorkoutSet[];
  notes?: string;
  syncStatus: SyncStatus;
  createdAt: string;
}

// v1.3 — LimeLog body metrics, consumed read-only by NCC.
//
// Mirrors LimeLog's `body_metrics` table: one row per (user, date) holding a
// morning body snapshot — bodyweight + any optional tape measurements the
// user opted into. LimeLog owns this table (push-only flow, same as
// workout_sessions/workout_sets): LimeLog writes, NCC reads via realtime +
// pull, never the reverse. There is intentionally no syncQueue entityType
// for body metrics in NCC — the suite hub displays them, it doesn't author
// them. SI units (kg/cm); display conversion is a UI concern.
//
// Progress photos are NOT here — they're LimeLog-local (WebView localStorage,
// never synced to Supabase for privacy), so NCC can't and shouldn't show them.
export interface BodyMetric {
  /** UUID, stable across sync (generated by LimeLog at log time). */
  id: string;
  /** YYYY-MM-DD local date this metric is FOR. */
  date: string;
  weightKg?: number;
  chestCm?: number;
  waistCm?: number;
  hipsCm?: number;
  armsCm?: number;
  legsCm?: number;
  notes?: string;
  /** Mirrors the row's sync state. Always 'synced' for NCC since NCC only
   *  ever pulls these rows — kept on the type for shape-parity with the
   *  other synced tables + the Dexie index. */
  syncStatus: SyncStatus;
  createdAt: string;
  updatedAt: string;
}
